"""The typed view M4 will render, pinned by a test rather than by a sample file.

Completion line 5 asks for a stable typed interface plus minimal sample data.
A hand-written JSON sample would be the second source of truth this module has
avoided everywhere else: it can drift from the shape the code returns and still
look authoritative. So the sample is produced *by* the real module here, its
required keys are asserted, and it is written to a file the M4 work can read.

Three things this pins that a renderer would otherwise guess at:

* Every field a surface needs is present in one payload -- steps, blocking
  reason with its event reference, evidence applicability, capability source,
  delivery tier. A surface that has to compute one of those itself will compute
  it differently from the next surface.
* Nothing in the payload is a progress estimate. There is no percentage, no
  elapsed time, no "expected finish": a step is ``done`` only on reported
  evidence, so a renderer has nothing to draw a timer from.
* A blocking reason is either complete with its event reference or explicitly
  ``unknown``. There is no empty-string reason for a surface to render as a
  blank row.
"""
from __future__ import annotations

import json

import pytest

from factory.control import issue_maintenance as im
from tests.test_issue_maintenance_core import (  # the same fakes, not a second set
    ACTOR, _request, tasks)

#: Where the sample lands for the M4 work to read. Regenerated by this test, so
#: it cannot describe a shape the module no longer returns.
SAMPLE = 'docs/implementation/webuddy-operations/m4-maintenance-sample.json'

REQUIRED = ('schema_version', 'task_id', 'revision', 'predecessor_id',
            'successor_id', 'status', 'issue', 'issue_digest', 'project_id',
            'baseline', 'agreement', 'expected_behaviour', 'delivery_goal',
            'delivery_tier', 'synthetic', 'execution_id', 'cost_usd',
            'blocking_reason', 'steps', 'delivery', 'receipts', 'created_at')

#: Words a progress bar would need. None of them may appear as a field name.
FORBIDDEN = ('percent', 'progress', 'eta', 'elapsed', 'remaining_s', 'deadline')


def _keys(payload, prefix=''):
    """Every field name in the payload, nested ones included."""
    found = []
    if isinstance(payload, dict):
        for key, value in payload.items():
            found.append(f'{prefix}{key}')
            found.extend(_keys(value, f'{prefix}{key}.'))
    elif isinstance(payload, list):
        for item in payload:
            found.extend(_keys(item, prefix))
    return found


def test_every_field_a_surface_needs_is_in_one_payload(tasks):
    view = tasks.create(_request(idempotency_key='m4-sample-1'), actor=ACTOR)
    missing = [key for key in REQUIRED if key not in view]
    assert not missing, f'M4 需要的字段缺失：{missing}'
    assert view['steps'] == [{'step': name, 'state': state} for name, state
                             in zip(im.MaintenanceTasks.STEPS,
                                    ['current'] + ['pending'] * 6)]
    assert view['blocking_reason'] is None, '没有阻塞时不应给出阻塞原因'


def test_nothing_in_the_payload_lets_a_surface_draw_a_timer(tasks):
    """别凭计时器编进度: there is no field a progress bar could read."""
    view = tasks.create(_request(idempotency_key='m4-sample-2'), actor=ACTOR)
    tasks.fake.advance(view['execution_id'], 'running')
    names = _keys(tasks.get(view['task_id'], actor=ACTOR))
    offenders = [name for name in names
                 if any(word in name.lower() for word in FORBIDDEN)]
    assert not offenders, f'这些字段会被画成进度：{offenders}'


def test_a_blocked_task_carries_its_reason_and_the_event_that_says_it(tasks):
    view = tasks.create(_request(idempotency_key='m4-sample-3'), actor=ACTOR)
    tasks.fake.advance(view['execution_id'], 'needs_human',
                       event='clarification.requested',
                       payload={'question': '跨月区间的边界以哪一天为准？'})
    blocked = tasks.get(view['task_id'], actor=ACTOR)
    assert blocked['status'] == 'waiting'
    reason = blocked['blocking_reason']
    assert reason['kind'] == 'clarification.requested'
    assert reason['message'] == '跨月区间的边界以哪一天为准？'
    assert reason['event'] == {'execution_id': view['execution_id'], 'sequence': 1}
    assert [step['state'] for step in blocked['steps']].count('blocked') == 1, \
        '等人回答要画成阻塞，不是进行中'


def test_the_sample_written_for_m4_is_produced_by_the_module_itself(tasks, tmp_path):
    """The sample file is regenerated from the real view, never hand-edited.

    A delivered task is used because it is the only state in which every branch
    of the payload is populated: delivery, evidence applicability, receipts.
    """
    view = tasks.create(_request(idempotency_key='m4-sample-4'), actor=ACTOR)
    tasks.fake.advance(view['execution_id'], 'running', event='run.started')
    tasks.fake.deliver(view['execution_id'], checks=[
        {'name': 'unit', 'passed': True, 'exit_code': 0, 'reused': False},
        {'name': 'lint', 'passed': True, 'exit_code': 0, 'reused': True,
         'identity_fingerprint': 'f' * 64}])
    tasks.export(view['task_id'], actor=ACTOR)
    delivered = tasks.get(view['task_id'], actor=ACTOR)

    assert delivered['status'] == 'delivered'
    # The receipt exists, so the last step is finished. Before the export it must
    # not be: a surface that shows the chain complete before the receipt is
    # written is showing a delivery nobody can point at.
    assert delivered['steps'][-1] == {'step': 'receipt', 'state': 'done'}
    assert delivered['delivery']['capability_source'] == 'platform_executor'
    assert delivered['delivery_tier'] in im.DELIVERY_TIERS
    assert len(delivered['receipts']) == 1
    # Applicability reaches the view, not only the receipt.
    assert [(c['name'], c['reused']) for c in delivered['delivery']['checks']] == [
        ('unit', False), ('lint', True)]

    # Timestamps and generated ids are replaced with fixed placeholders. Left as
    # they are, the file would change on every run and every regeneration would
    # look like a shape change in review.
    stable = {**delivered, 'task_id': 'sample-task', 'created_at': '2026-01-01T00:00:00+00:00',
              'receipts': [{**receipt, 'task_id': 'sample-task',
                            'at': '2026-01-01T00:00:00+00:00'}
                           for receipt in delivered['receipts']]}
    sample = {'note': '由 tests/test_issue_maintenance_view_contract.py 生成，勿手工编辑；'
                      '时间与 id 已替换为固定占位值；合成示例，不代表任何客户数据。',
              'schema_version': im.SCHEMA_VERSION, 'task': stable}
    text = json.dumps(sample, ensure_ascii=False, indent=2, sort_keys=True) + '\n'
    from pathlib import Path
    target = Path(__file__).resolve().parent.parent / SAMPLE
    target.write_text(text, encoding='utf-8')
    assert json.loads(target.read_text(encoding='utf-8'))['task']['status'] == 'delivered'


def test_the_last_step_is_not_finished_until_a_receipt_exists(tasks):
    """Both directions, because only the pair distinguishes them.

    Asserting only the post-export ``done`` would pass just as well if the step
    were hardcoded to ``done`` from the moment the execution delivered.
    """
    view = tasks.create(_request(idempotency_key='m4-sample-5'), actor=ACTOR)
    tasks.fake.deliver(view['execution_id'])
    before = tasks.get(view['task_id'], actor=ACTOR)
    assert before['receipts'] == []
    assert before['steps'][-1] == {'step': 'receipt', 'state': 'current'}

    tasks.export(view['task_id'], actor=ACTOR)
    after = tasks.get(view['task_id'], actor=ACTOR)
    assert after['steps'][-1] == {'step': 'receipt', 'state': 'done'}
