import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { request } from '../workspace/api'
import { ErrorNotice, errorText, formatDate, type PageProps } from './ui'
export type Proposal = {id:string;kind:string;source:string;status:string;revision:number;manifest_revision:number;result_revision?:number;created_at:string;evidence:{run_ids:string[];explanation:string};change:Record<string,unknown>}
const kinds:Record<string,string>={add_skill:'加入 skill',remove_skill:'移除 skill',upgrade_skill:'升级 skill 版本',add_assertion:'新增断言'}
export default function AgentEvolution({agentId,onChanged,...props}:PageProps & {agentId:string;onChanged:()=>void}) {
  const [items,setItems]=useState<Proposal[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false)
  const load=useCallback(async(signal?:AbortSignal)=>{const value=await request<{proposals:Proposal[]}>(`/api/v4/agents/${encodeURIComponent(agentId)}/evolution`,{signal,onUnauthorized:props.onUnauthorized});if(!signal?.aborted){setItems(value.proposals);setLoaded(true)}},[agentId,props.onUnauthorized])
  useEffect(()=>{const c=new AbortController();void load(c.signal).catch(e=>{if(!c.signal.aborted)setError(errorText(e))});return()=>c.abort()},[load])
  const decide=async(p:Proposal,approve:boolean)=>{setBusy(true);setError('');try{await request(`/api/v4/evolution/${encodeURIComponent(p.id)}/decision`,{method:'POST',csrfToken:props.csrfToken,onUnauthorized:props.onUnauthorized,body:{approve,revision:p.revision}});await load();onChanged()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
  return <section className="wb-card agent-manifest" aria-label="证据驱动进化"><h2>进化提案</h2><p>有证据才提案。批准会生成新清单 revision，只影响后续任务。</p>{error&&<ErrorNotice message={error}/>} {loaded&&!items.length&&<p>暂无进化提案。可从经验库升格 skill，或等待每周使用统计。</p>}
    {items.map(p=><article key={p.id}><h3>{kinds[p.kind]||p.kind} · {p.status==='pending'?'待审':p.status==='approved'?'已批准':'已驳回'}</h3><p>来源：{p.source==='capability'?'运行沉淀':p.source==='usage'?'使用统计':'人工提案'} · {formatDate(p.created_at)} · 基于 revision {p.manifest_revision}</p><pre>{JSON.stringify(p.change,null,2)}</pre><p>{p.evidence.explanation}</p><div>{p.evidence.run_ids.map(id=><Link key={id} to={`/runs/${encodeURIComponent(id)}`}>证据运行 {id.slice(0,8)} </Link>)}</div>{p.result_revision&&<p>清单 revision {p.result_revision}</p>}{props.user?.role==='admin'&&p.status==='pending'&&<div><button className="wb-button wb-button-primary" disabled={busy} onClick={()=>void decide(p,true)}>批准提案</button><button className="wb-button wb-button-secondary" disabled={busy} onClick={()=>void decide(p,false)}>驳回提案</button></div>}</article>)}
  </section>
}
export function EvolutionPolicy({projectId,csrfToken,onUnauthorized,isAdmin}:Pick<PageProps,'csrfToken'|'onUnauthorized'> & {projectId:string;isAdmin:boolean}) {
  const [policy,setPolicy]=useState<{revision:number;auto_evolve:boolean;notifications:boolean}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const path=`/api/v4/projects/${encodeURIComponent(projectId)}/evolution-policy`
  useEffect(()=>{const c=new AbortController();void request<typeof policy>(path,{signal:c.signal,onUnauthorized}).then(p=>{if(!c.signal.aborted)setPolicy(p)}).catch(e=>{if(!c.signal.aborted)setError(errorText(e))});return()=>c.abort()},[path,onUnauthorized])
  const save=async()=>{if(!policy)return;setBusy(true);setError('');try{setPolicy(await request(path,{method:'PUT',body:policy,csrfToken,onUnauthorized}))}catch(e){setError(errorText(e))}finally{setBusy(false)}}
  return <section className="wb-card agent-manifest"><h2>职能体进化策略</h2><p>默认人工审批。自动模式仅允许本项目绑定岗位的运行沉淀加入、连续未引用移除；身份段和断言仍需人工批准。</p>{error&&<ErrorNotice message={error}/>} {policy&&<><label><input type="checkbox" checked={policy.auto_evolve} disabled={!isAdmin||busy} onChange={e=>setPolicy({...policy,auto_evolve:e.target.checked})}/>允许有证据的自动进化</label><label><input type="checkbox" checked={policy.notifications} disabled={!isAdmin||busy} onChange={e=>setPolicy({...policy,notifications:e.target.checked})}/>通过运维通道通知进化结果</label>{isAdmin&&<button disabled={busy} onClick={()=>void save()}>保存进化策略</button>}</>}</section>
}
export function PromoteSkill({capabilityId,revision,sourceRunId,...props}:PageProps & {capabilityId:string;revision:number;sourceRunId?:string}) {
  const [agents,setAgents]=useState<Array<{id:string;name:string}>>([]),[aid,setAid]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
  useEffect(()=>{if(!sourceRunId)return;const c=new AbortController();void request<{agents:Array<{id:string;name:string}>}>('/api/v4/agents',{signal:c.signal,onUnauthorized:props.onUnauthorized}).then(v=>{if(!c.signal.aborted){if(!Array.isArray(v.agents))throw new Error('岗位列表暂不可用');setAgents(v.agents)}}).catch(e=>{if(!c.signal.aborted)setNotice(errorText(e))});return()=>c.abort()},[sourceRunId,props.onUnauthorized])
  const promote=async()=>{setBusy(true);try{const p=await request<Proposal>(`/api/v4/capabilities/${encodeURIComponent(capabilityId)}/promote`,{method:'POST',body:{agent_id:aid,revision},csrfToken:props.csrfToken,onUnauthorized:props.onUnauthorized});setNotice(p.status==='approved'?'已升格并按项目策略批准。':p.status==='rejected'?'该版本的提案已驳回；请更新能力版本后重新升格。':'已生成 skill 草稿与有证据的加入提案。')}catch(e){setNotice(errorText(e))}finally{setBusy(false)}}
  return <section className="agent-manifest"><h3>升格为 skill</h3>{sourceRunId?<><label>目标职能体<select value={aid} onChange={e=>setAid(e.target.value)}><option value="">选择长期岗位</option>{agents.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><button disabled={!aid||busy} onClick={()=>void promote()}>升格为 skill</button>{notice&&<p role="status">{notice}</p>}{aid&&<Link to={`/agents/${encodeURIComponent(aid)}`}>查看目标岗位与进化提案</Link>}</>:<p>没有来源运行证据，不能升格。</p>}</section>
}
