// @vitest-environment jsdom
import {afterEach,beforeEach,expect,it,vi} from 'vitest'
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react'
import {MemoryRouter} from 'react-router-dom'
import {request} from '../workspace/api'
import AgentEvolution,{EvolutionPolicy,PromoteSkill} from './AgentEvolution'
vi.mock('../workspace/api',async original=>({...await original<typeof import('../workspace/api')>(),request:vi.fn()}))
const api=vi.mocked(request),changed=vi.fn(),props={csrfToken:'csrf',onUnauthorized:vi.fn(),user:{id:1,username:'admin',role:'admin' as const}}
const p={id:'proposal',kind:'remove_skill',source:'usage',status:'pending',revision:1,manifest_revision:2,created_at:'2026-09-14T00:00:00Z',evidence:{run_ids:['run123456'],explanation:'五次没有证据引用'},change:{id:'s1',version:1}}
beforeEach(()=>{api.mockReset();changed.mockReset();api.mockResolvedValue({proposals:[p]})});afterEach(cleanup)
it('renders evidence and approves using proposal revision, then refreshes the manifest',async()=>{render(<MemoryRouter><AgentEvolution agentId="a1" {...props} onChanged={changed}/></MemoryRouter>);await screen.findByText('五次没有证据引用');expect(screen.getByRole('link',{name:/证据运行/}).getAttribute('href')).toBe('/runs/run123456');fireEvent.click(screen.getByRole('button',{name:'批准提案'}));await waitFor(()=>expect(changed).toHaveBeenCalled());expect(api).toHaveBeenCalledWith('/api/v4/evolution/proposal/decision',expect.objectContaining({body:{approve:true,revision:1}}))})
it('rejects proposals and retains an actionable error after conflict',async()=>{render(<MemoryRouter><AgentEvolution agentId="a1" {...props} onChanged={changed}/></MemoryRouter>);await screen.findByRole('button',{name:'驳回提案'});api.mockRejectedValueOnce(new Error('清单已变更'));fireEvent.click(screen.getByRole('button',{name:'驳回提案'}));await screen.findByText('清单已变更');expect(api).toHaveBeenCalledWith('/api/v4/evolution/proposal/decision',expect.objectContaining({body:{approve:false,revision:1}}));expect(changed).not.toHaveBeenCalled()})
it('members can read evidence but cannot decide',async()=>{render(<MemoryRouter><AgentEvolution agentId="a1" {...props} user={{...props.user,role:'member'}} onChanged={changed}/></MemoryRouter>);await screen.findByText('五次没有证据引用');expect(screen.queryByRole('button',{name:'批准提案'})).toBeNull()})
it('project auto-evolve is off by default and saves notification preference with CAS',async()=>{api.mockResolvedValue({revision:0,auto_evolve:false,notifications:true});render(<EvolutionPolicy projectId="p1" {...props} isAdmin/>);const box=await screen.findByLabelText('允许有证据的自动进化');expect((box as HTMLInputElement).checked).toBe(false);fireEvent.click(box);fireEvent.click(screen.getByLabelText('通过运维通道通知进化结果'));fireEvent.click(screen.getByText('保存进化策略'));await waitFor(()=>expect(api).toHaveBeenCalledWith('/api/v4/projects/p1/evolution-policy',expect.objectContaining({body:{revision:0,auto_evolve:true,notifications:false}})))})
it('promotes a sourced capability and prevents promotion without evidence',async()=>{api.mockResolvedValue({agents:[{id:'a1',name:'维护岗'}]});const view=render(<MemoryRouter><PromoteSkill capabilityId="c1" revision={3} sourceRunId="r1" {...props}/></MemoryRouter>);await screen.findByRole('option',{name:'维护岗'});fireEvent.change(screen.getByLabelText('目标职能体'),{target:{value:'a1'}});api.mockResolvedValueOnce({status:'pending'});fireEvent.click(screen.getByRole('button',{name:'升格为 skill'}));await screen.findByText('已生成 skill 草稿与有证据的加入提案。');expect(api).toHaveBeenCalledWith('/api/v4/capabilities/c1/promote',expect.objectContaining({body:{agent_id:'a1',revision:3}}));view.unmount();render(<MemoryRouter><PromoteSkill capabilityId="c2" revision={1} {...props}/></MemoryRouter>);expect(screen.queryByRole('button',{name:'升格为 skill'})).toBeNull()})
