import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { request, WorkspaceApiError } from '../workspace/api'
import { EmptyState, ErrorNotice, PageHeader, errorText, type PageProps } from './ui'
import type { OverviewData } from './v3-types'


export default function CostsPage({ onUnauthorized }: PageProps) {
  const [data, setData] = useState<OverviewData | null>(null); const [error, setError] = useState<string | null>(null); const [refreshIndex, setRefreshIndex] = useState(0)
  useEffect(() => { const controller = new AbortController(); setError(null); void request<OverviewData>('/api/v3/overview', { onUnauthorized, signal: controller.signal }).then((value) => { if (!controller.signal.aborted) setData(value) }).catch((cause) => { if (!controller.signal.aborted && !(cause instanceof WorkspaceApiError && cause.status === 401)) setError(errorText(cause)) }); const timer = window.setInterval(() => setRefreshIndex((value) => value + 1), 5000); return () => { controller.abort(); window.clearInterval(timer) } }, [onUnauthorized, refreshIndex])
  return <div className="wb-page"><PageHeader title="调用记录" description="查看模型和调用次数。计费与 token 额度由中转站统一管理。" actions={<><button className="wb-button wb-button-secondary" onClick={() => setRefreshIndex((value) => value + 1)}>刷新</button><Link className="wb-button wb-button-secondary" to="/settings/runtime">运行配置</Link></>} />{error && <ErrorNotice message={error} />}{!data && !error && <div className="wb-card"><div className="wb-list-placeholder"><span /><span /><span /></div></div>}{data && <><div className="wb-cost-summary"><article><span>运行总数</span><strong>{data.runs}</strong><small>包含规划与执行</small></article></div><section className="wb-card wb-cost-card"><div className="wb-card-head"><div><span className="wb-eyebrow">真实调用记录</span><h2>按角色查看</h2><p>模型 ID 和 provider 来自运行时配置与运行事件，空配置不会被页面补成假数据。</p></div></div>{data.model_usage.length === 0 ? <EmptyState title="还没有调用记录" description="运行产生调用记录后，这里会显示角色、provider、模型和调用次数。" /> : <div className="wb-table-wrap"><table className="wb-table"><thead><tr><th>角色</th><th>Provider</th><th>模型</th><th>调用次数</th></tr></thead><tbody>{data.model_usage.map((item, index) => <tr key={`${item.profile}-${item.provider ?? 'unknown'}-${item.model ?? 'unknown'}-${index}`}><td><strong>{item.profile}</strong></td><td className="wb-mono">{item.provider || '未记录'}</td><td className="wb-mono">{item.model || '未配置'}</td><td>{item.calls}</td></tr>)}</tbody></table></div>}</section><section className="wb-card wb-cost-note"><strong>计费管理</strong><span>费用及 token 配额请在中转站查看和管理，webuddy 不进行本地计费或额度拦截。</span></section></>}</div>
}
